name: GitHub CICD

on:
  push:
    branches:
      - "v[0-9]+.[0-9]+"

jobs:
  job1:
    if: ${{ startsWith(github.event.head_commit.message, '#norun') != true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: "table"
          ignore-unfixed: true
          severity: "CRITICAL"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kimzhao1307/kim-zhaochen:latest

      - name: Send GitHub Action trigger data to Slack workflow
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "Image build and signed"
          SLACK_MESSAGE: |
            Name: ZHAO CHEN
            Matriculation: A0269561U
            Email: e1112944@u.nus.edu
            GitHub: https://github.com/Kim-ZhaoChen/github-ci-cd
            Docker: https://hub.docker.com/repository/docker/username/repo/general
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
